const DATA=[
{id:'phase1',tab:'Phase 1',title:'Phase 1 — Broker & Dukes opening',desc:'Early story, phone basics, first friends, and first side systems.',note:'Rule of thumb: when a blue random-character icon appears, do it before blasting through lots of story missions.',groups:[
{name:'Story missions — do in order',items:['The Cousins Bellic','It\'s Your Call','Three\'s a Crowd','First Date','Bleed Out','Easy Fare','Jamaican Heat','Bull in a China Shop','Hung Out to Dry','Clean Getaway','Ivan the Not So Terrible','Concrete Jungle','Uncle Vlad','Crime and Punishment','Do You Have Protection?','Shadow','Final Destination','No Love Lost','Logging On','Rigged to Blow','Search and Delete','Easy as Can Be','The Master and the Molotov','Russian Revolution','Roman\'s Sorrow']},
{name:'Do before pushing too far',items:[['Make a rotating manual save after Roman\'s Sorrow','Save','warn'],['Little Jacob is available after Shadow — start friendship slowly','Friend'],['Start Little Jacob drug deliveries after Shadow','Side'],['Win darts once when convenient','Activity'],['Win pool once when convenient','Activity'],['Check for Brian random encounters','Random','warn']]}
]},
{id:'phase2',tab:'Phase 2',title:'Phase 2 — Bohan & Algonquin opens',desc:'Brucie, races, Packie intro, and the first major side-content wave.',note:'After Algonquin opens, slow down. Mix side content between story missions so the endgame cleanup is less painful.',groups:[
{name:'Story missions — do in order',items:['Out of the Closet','No. 1','Escuela of the Streets','Street Sweeper','Luck of the Irish','Blow Your Cover','The Puerto Rican Connection','The Snow Storm','Have a Heart','Call and Collect','Harboring a Grudge','Waste Not Want Knots','Three Leaf Clover']},
{name:'Do alongside this phase',items:[['Brucie becomes a friend after No. 1 — start his checklist','Friend'],['Win Brucie race: South Broker','Race'],['Win Brucie race: Airport Run','Race'],['Win Brucie race: Dukes Boulevard','Race'],['Complete several Little Jacob deliveries','Side'],['Start Most Wanted in unlocked boroughs','Police'],['Make a second manual save after Three Leaf Clover','Save','warn']]}
]},
{id:'phase3',tab:'Phase 3',title:'Phase 3 — Algonquin main stretch',desc:'Most friend work and many random characters fit best here.',note:'This is the sweet spot for friendship activities: Little Jacob, Brucie, and Packie should all be worked on now.',groups:[
{name:'Story missions — do in order',items:['Actions Speak Louder than Words','I Need Your Clothes, Your Boots, and Your Motorcycle','Smackdown','Babysitting','Tunnel of Death','Blood Brothers','Undertaker','Museum Piece','No Way on the Subway','Weekend at Florian\'s','Late Checkout','Hating the Haters','Union Drive','Buoys Ahoy','Truck Hustle','Pegorino\'s Pride']},
{name:'Recommended completion work',items:[['Finish all Little Jacob activities','Friend','warn'],['Finish all Brucie activities','Friend','warn'],['Start Packie activities','Friend','warn'],['Win QUB3D high score','Activity'],['Do random characters you have unlocked','Random','warn'],['Complete more races and police computer work','Side']]}
]},
{id:'phase4',tab:'Phase 4',title:'Phase 4 — Alderney & big cleanup',desc:'Alderney opens up the last major island content and late side missions.',groups:[
{name:'Story missions — do in order',items:['Payback','Catch the Wave','Trespass','To Live and Die in Alderney','Entourage','Dining Out','Liquidize the Assets','That Special Someone']},
{name:'Do before the final stretch',items:[['Finish Packie activities and unlock car bombs','Friend','miss'],['Finish Jacob and Brucie abilities if not done','Friend','miss'],['Complete Fixer assassinations as they unlock','Side'],['Complete remaining Brucie races','Race'],['Complete Most Wanted by borough','Police'],['Complete 20 Vigilante crimes','Police'],['Begin Stevie car thefts once available','Cars']]}
]},
{id:'phase5',tab:'Finale',title:'Phase 5 — Finale and post-story cleanup',desc:'Finish the story, then clean up collectibles and any missed open-world tasks.',note:'Either final path counts for in-game 100%. Keep a manual save before choosing if you want to see both endings.',groups:[
{name:'Final story checklist',items:[['Make a manual save before the final choice','Save','warn'],['One Last Thing','Story'],['Complete final ending path','Story']]},
{name:'Post-story cleanup order',items:[['Finish all random character encounters','Random'],['Finish Stevie\'s 30 car thefts','Cars'],['Finish remaining police computer tasks','Police'],['Finish remaining activities: bowling, darts, pool, QUB3D','Activity'],['Do 50 stunt jumps','Collectible'],['Collect 200 flying rats','Collectible'],['Check Stats screen for 100%','Final','warn']]}
]},
{id:'friends',tab:'Friends',title:'Friendship tracker — required for 100%',desc:'For in-game 100%, focus on Little Jacob, Brucie, and Packie.',groups:[
{name:'Little Jacob',items:[['Darts with Little Jacob','Friend'],['Drinking with Little Jacob','Friend'],['Eating with Little Jacob','Friend'],['Pool with Little Jacob','Friend'],['Show with Little Jacob','Friend'],['Strip Club with Little Jacob','Friend'],['Unlock Discount Guns ability','Ability','warn']]},
{name:'Brucie',items:[['Boating with Brucie','Friend'],['Bowling with Brucie','Friend'],['Drinking with Brucie','Friend'],['Eating with Brucie','Friend'],['Helicopter ride with Brucie','Friend'],['Show with Brucie','Friend'],['Strip Club with Brucie','Friend'],['Unlock Helicopter Rides ability','Ability','warn']]},
{name:'Packie',items:[['Bowling with Packie','Friend'],['Darts with Packie','Friend'],['Drinking with Packie','Friend'],['Pool with Packie','Friend'],['Show with Packie','Friend'],['Strip Club with Packie','Friend'],['Unlock Car Bombs ability','Ability','warn']]},
{name:'Optional friend achievements',items:[['Unlock Roman taxi ability','Optional','opt'],['Unlock Dwayne backup ability','Optional','opt'],['All available friends above 90% for Liberty City (5)','Achievement','opt']]}
]},
{id:'side',tab:'Side',title:'Side content — required for 100%',desc:'Mark these off whenever you complete them.',groups:[
{name:'Little Jacob drug deliveries — 10',items:Array.from({length:10},(_,i)=>`Drug delivery ${i+1}`)},
{name:'Fixer assassinations — 9',items:Array.from({length:9},(_,i)=>`Assassination ${i+1}`)},
{name:'Brucie Exotic Exports — 10',items:Array.from({length:10},(_,i)=>`Exotic Export ${i+1}`)},
{name:'Stevie car thefts — 30',items:Array.from({length:30},(_,i)=>`Stevie car theft ${i+1}`)},
{name:'Brucie races — 9',items:['South Broker','Airport Run','Dukes Boulevard','South Algonquin','Star Junction','Road to Bohan','North Alderney','Elevated','South Alderney']},
{name:'Police computer',items:[...Array.from({length:20},(_,i)=>`Vigilante crime ${i+1}/20`),...['Broker Most Wanted 1','Broker Most Wanted 2','Broker Most Wanted 3','Broker Most Wanted 4','Broker Most Wanted 5','Broker Most Wanted 6','Dukes/Bohan Most Wanted 1','Dukes/Bohan Most Wanted 2','Dukes/Bohan Most Wanted 3','Dukes/Bohan Most Wanted 4','Dukes/Bohan Most Wanted 5','Dukes/Bohan Most Wanted 6','Algonquin Most Wanted 1','Algonquin Most Wanted 2','Algonquin Most Wanted 3','Algonquin Most Wanted 4','Algonquin Most Wanted 5','Algonquin Most Wanted 6','Alderney Most Wanted 1','Alderney Most Wanted 2','Alderney Most Wanted 3','Alderney Most Wanted 4','Alderney Most Wanted 5','Alderney Most Wanted 6']]},
{name:'Random characters required for 100%',items:['Brian 1','Brian 2','Brian 3','Eddie Low 1','Eddie Low 2','Gracie','Hossan','Ilyena','Marnie 1','Marnie 2','Mel','Pathos 1','Pathos 2','Real Badman','Sara 1','Sara 2']},
{name:'Activities required for 100%',items:['Win full game of Bowling','Win Darts','Win Pool','Beat QUB3D high score 10,950+']}
]},
{id:'collectibles',tab:'Collectibles',title:'Collectibles — endgame grind',desc:'Best saved for cleanup with a map/guide open.',note:'This app tracks counts. Use a map for exact locations unless you enjoy hunting.',groups:[
{name:'Unique stunt jumps — 50',items:Array.from({length:50},(_,i)=>`Stunt jump ${i+1}`)},
{name:'Flying rats / pigeons — 200',items:Array.from({length:200},(_,i)=>`Flying rat ${i+1}`)}
]},
{id:'steam',tab:'Steam',title:'Steam achievement extras',desc:'Not all are required for in-game 100%, but they are worth tracking.',groups:[
{name:'Achievement goals',items:[['Finish story under 30 hours: Liberty City Minute','Achievement','opt'],['Complete all 5 helicopter tours: Sightseer','Achievement','opt'],['Fly under 14 main bridges: Under The Radar','Achievement','opt'],['Meet all random characters: No More Strangers','Achievement','opt'],['Unlock Roman taxi ability: Driving Mr. Bellic','Achievement','opt'],['All available friends above 90%: Liberty City (5)','Achievement','opt'],['Escape a 6-star wanted level','Achievement','opt'],['Survive 5 minutes on 6-star wanted level','Achievement','opt']]}
]},
{id:'extra',tab:'Extras',title:'Optional Liberty City bucket list',desc:'Cool stuff to see during a modern replay. Not required for 100%.',groups:[
{name:'Easter eggs and vibes',items:[['Find the beating heart inside the Statue of Happiness','Easter egg','opt'],['Try the swing-set launch glitch','Easter egg','opt'],['Take a taxi ride without skipping','Vibe','opt'],['Ride the subway across boroughs','Vibe','opt'],['Watch a full comedy show','Vibe','opt'],['Watch a full cabaret show','Vibe','opt'],['Browse internet café websites','Vibe','opt'],['Listen to each radio station for 10 minutes','Vibe','opt'],['Watch a rainy Liberty City night from a cab','Vibe','opt'],['Explore the airport and docks','Vibe','opt']]}
]}
];